### ISSUE TITLE
Only english as system language seems to work

### ISSUE THREAD

**Issue by zwerch** [CamHenlin/imessageclient#1]
```
➜  node app
we have a file to monitor!
Error: /Users/me/Developer/imessageclient/sendmessage_single.AppleScript:167:179: execution error: System Events got an error: Can’t get menu "file" of menu bar 1 of process "Messages". (-1728)

    at ChildProcess.<anonymous> (/Users/me/Developer/imessageclient/node_modules/applescript/lib/applescript.js:54:13)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
```

Maybe there is a way todo this in AppleScript without using the captions of the menubar items, but instead the keystrokes or some events.

**Comment by CamHenlin** [comment]
Hmm, yeah, good idea. is cmd+n still "new message" with your default language?

**Comment by CamHenlin** [comment]
I believe I just fixed this by counting menu items instead. Could you give it a shot and confirm?

**Comment by zwerch** [comment]
Yeah, seems to work, thanks :+1:
