### ISSUE TITLE
Crash on message send

### ISSUE THREAD

**Issue by ksloan** [CamHenlin/imessageclient#13]
Sent a message and got this:

    Error: /Users/kevin/Dropbox/fundev/imessageclient/sendmessage_single.AppleScript:130:142: execution error: System Events got an error: Can’t get process "Messages". (-1728)

    at ChildProcess.<anonymous> (/Users/kevin/Dropbox/fundev/imessageclient/applescript/lib/applescript.js:54:13)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:807:12)

**Comment by rioniac** [comment]
I just got the exact same issue.  Well, of course with different paths.

**Comment by mkBlaze** [comment]
Messages.app has to be open for this to work.

**Comment by CamHenlin** [comment]
Looks like you probably don't have messages open
