### ISSUE TITLE
Crash when sending message

### ISSUE THREAD

**Issue by thibmaek** [CamHenlin/imessageclient#17]
Crashes when trying to send a message trough AppleScript:
we have a file to monitor!

```
Error: /Users/thibaultmaekelbergh/Downloads/imessageclient-master/sendmessage_single.AppleScript:130:142: execution error: System Events got an error: Can’t get process "Messages". (-1728)

    at ChildProcess.<anonymous> (/Users/thibaultmaekelbergh/Downloads/imessageclient-master/applescript/lib/applescript.js:54:13)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

**Comment by CamHenlin** [comment]
You must have messages open
